### ISSUE TITLE
Can't choose h264_nvenc codec anymore

### ISSUE THREAD

**Issue by rbo23** [argorar/WebMConverter#100]
**Describe the bug**
Version 3.41.0 Can't convert to h264 with acceleration...

**To Reproduce**
1. Enable  "Activate mp4 conversion" and "Hardware acceleration (NVIDIA)"
2. Uncheck "Use H265"
3. Codec is hevc_nvenc

**Expected behavior**
Be able to choose h264_nvenc codec as it was before

**Comment by argorar** [comment]
Paste output log and hardware specifications. That can be related to drivers and cuda support.

**Comment by rbo23** [comment]
> Paste output log and hardware specifications. That can be related to drivers and cuda support, update to latest version.

It works perfectly fine in previous version... It just started to use hevc_nvenc codec instead of h264_nvenc when I select "Hardware acceleration". Also "Use H265" option doesn't change anything for me
windows 10 22H2
rtx 3080, Latest 566.03 driver
Ryzen 5 5600X



https://github.com/user-attachments/assets/5df45798-d894-4739-9d3f-015907596d2a

**Comment by argorar** [comment]
h264_nvenc doesn’t support HDR10bits. 

> **Expected behavior**
> Be able to choose h264_nvenc codec as it was before 

As the evidence show you doesn’t have problem coding with hevc_nvenc, any specific reason to need h264_nvenc?

To use H265 uncheck hardware acceleration, is not supported .

**Comment by rbo23** [comment]
> any specific reason to need h264_nvenc?
It encodes much faster than libx264. 
> h264_nvenc doesn’t support HDR10bits.
Oh, ok, didn't know that. Maybe add some sort of preset selector to easier apply settings rather than change the ffmpeg arguments every time. I just liked the way h264_nvenc was enabled by default

**Comment by argorar** [comment]
In latest version is more easy to select codec.
