### ISSUE TITLE
Unknown AviSynth colorspace

### ISSUE THREAD

**Issue by rbo23** [argorar/WebMConverter#101]
Hi! I've tried to convert this hdr10 video on version 3.41.0
https://isovideo.com/SDR_to_HDR_Up_Conversion_Examples/Sony_Fireworks_4K_Demo-183960-tmu_hdr10_hevc.mkv
Got an error. What am I doing wrong?
![image](https://github.com/user-attachments/assets/0df54a88-ee32-42f6-a1ab-0b2f1d85c8d9)

**Comment by argorar** [comment]
As documentation say:
* Requires [AviSynth](https://sourceforge.net/projects/avisynth2/) (2.6.0, 32-bit)

[Sony_Fireworks_4K_Demo-183960-tmu_hdr10_hevc.webm](https://github.com/user-attachments/assets/2f46e9cb-49b1-4687-9c7b-280fc189c498)
