### ISSUE TITLE
Suggestion: Merging audio tracks

### ISSUE THREAD

**Issue by MrMeidi** [argorar/WebMConverter#102]
Hello!

First of all, love your app and thank you for making and supporting it, I use it pretty much daily.
But since I've been using it for so long, I really wish it'd have one single feature that I feel like it's missing: being able to merge audio tracks instead of selecting one particular track after loading the video file. I've looked all over the app and haven't found it.

One particular use case for this feature is NVIDIA ShadowPlay: it allows the user to split game/mic audio into 2 tracks and it's a really nice feature when you don't need your own voice on some particular videos. But sadly when it comes to this app - it becomes very troublesome to make a clip with it when you want both tracks, since you'd have to use some other editor to merge audio first, which kills the whole purpose.

Would love to see this feature getting added, if possible.

**Comment by argorar** [comment]
Sharing a test file would be helpful.

**Comment by MrMeidi** [comment]
Of course, here's a super short ShadowPlay file with 2 audio tracks. Pasting it into WebMConverter gives the "Select Track" popup.

https://github.com/user-attachments/assets/3884349b-e9c2-4e51-a9cc-fefcb9b24a9e

**Comment by argorar** [comment]
Now you can mix **only two tracks**, check latest update. Design a graphic interface would be more time consuming so that would be the implementation so far.

**Comment by MrMeidi** [comment]
Thank you so much! Tried it, it's exactly what I wanted and now the app is fully compatible with ShadowPlay.

As for 2 tracks: yeah, I think it serves the purpose just fine, I myself don't see any situations where one video would have more than 2 different tracks that are all synced to each other and don't overlay one another. ShadowPlay's split is the most I've ever seen.

Thanks again, this is a really great feature for gaming recordings.
