### ISSUE TITLE
webms with full range color aren't playing in Chrome 

### ISSUE THREAD

**Issue by ll811** [argorar/WebMConverter#103]
**Describe the bug**
webms with the latest version 3.41.1 aren't playing in Chrome, they're stuck on the first frame.  Seems to only affect webms with full color range. There used to be a separate issue where Chrome crushed the blacks on full range webms that seems fixed however the webms aren't playing. Colors also don't seem to be a 1:1 match with the file in Chrome based on the still frame, but I suppose that's a separate issue, looks as it should in Firefox.

**To Reproduce**
1. Convert a webm with full range color 
2. Open it with Chrome 
3. See error

**Software version(please complete the following information):**
 - Avisynth: 2.6

**Test File**
[test.webm](https://github.com/user-attachments/assets/febf627b-59d2-4422-9735-8afcf9459af4)

**Comment by argorar** [comment]
Add test file, **original source**.

**Comment by ll811** [comment]
> Add test file, **original source**.

Already deleted original source so had to record a new one. Made a new webm with it.

[test 2.webm](https://github.com/user-attachments/assets/f1bbf0d2-ff6d-45ac-a384-77f4c3498fa8)

Test source
https://files.catbox.moe/6yqkfw.mkv

**Comment by argorar** [comment]
catbox link doesn't work.

**Comment by ll811** [comment]
> catbox link doesn't work.

It should. Automatically downloads when I click it. Anyways here's a mega link 
https://mega.nz/file/BRF2HaiL#_f_O4TGCPX3BaWyJ6sZ7gXgT0N0ljgbCIuFCii1ZDVI

**Comment by argorar** [comment]
Check latest update.
