### ISSUE TITLE
10bit non-HDR videos have messed up colors

### ISSUE THREAD

**Issue by DoTheSneedful** [argorar/WebMConverter#104]
**Describe the bug**
When converting a 10bit video the colors get messed up, and looks like it's because a recent update detects it as HDR.

**To Reproduce**
1. Try to convert a 10bit h.265 video

**Expected behavior**
Colors are maintained

**Screenshots**
![colors](https://github.com/user-attachments/assets/f58fae6b-9fb9-4cd4-8837-21a164fc684e)

**Software version(please complete the following information):**
 - Avisynth: 

**Test File**
[test.zip](https://github.com/user-attachments/files/17626506/test.zip)

**Comment by argorar** [comment]
At my side is detected as yuv420p10.
![imagen](https://github.com/user-attachments/assets/ea115bae-92c3-4c47-a318-d1d429adc716)

Check latest update.

If this project is helpful for you give a star ⭐

**Comment by kirbco** [comment]
> At my side is detected as yuv420p10. ![imagen](https://private-user-images.githubusercontent.com/9936760/383199161-ea115bae-92c3-4c47-a318-d1d429adc716.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODg4MTMsIm5iZiI6MTczMjE4ODUxMywicGF0aCI6Ii85OTM2NzYwLzM4MzE5OTE2MS1lYTExNWJhZS05MmMzLTRjNDctYTMxOC1kMWQ0MjlhZGM3MTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjFUMTEyODMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjlhNzVmYWZjNWQ5YThjZmE0NjdmMTM4NGExOTg4MTg2YTY3YjU0NDBiNzAzZmEzNTA4NDc1MTZiYTUxMmRkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lZcWXetaTNI4jD9pR4gFwGjD9N-1jtx4ylKli3KMoyg)
> 
> Check latest update.
> 
> If this project is helpful for you give a star ⭐

I understand the issue's been closed but I've been having the same and have the most updated version. What exactly is the screenshot showing? What did you change?

**Comment by argorar** [comment]
> > At my side is detected as yuv420p10. ![imagen](https://private-user-images.githubusercontent.com/9936760/383199161-ea115bae-92c3-4c47-a318-d1d429adc716.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODg4MTMsIm5iZiI6MTczMjE4ODUxMywicGF0aCI6Ii85OTM2NzYwLzM4MzE5OTE2MS1lYTExNWJhZS05MmMzLTRjNDctYTMxOC1kMWQ0MjlhZGM3MTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjFUMTEyODMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjlhNzVmYWZjNWQ5YThjZmE0NjdmMTM4NGExOTg4MTg2YTY3YjU0NDBiNzAzZmEzNTA4NDc1MTZiYTUxMmRkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lZcWXetaTNI4jD9pR4gFwGjD9N-1jtx4ylKli3KMoyg)
> > Check latest update.
> > If this project is helpful for you give a star ⭐
> 
> I understand the issue's been closed but I've been having the same and have the most updated version. What exactly is the screenshot showing? What did you change?

Upload a short clip to test.

**Comment by kirbco** [comment]
That's odd. It doesn't look messed up when I upload it but this is what it looks like when I play it.

![Cat People 1982 REMASTERED 1080p BluRay x265-RARBG webm_000000 000](https://github.com/user-attachments/assets/4731be6f-1053-4f54-963c-9a2ea7ef8f0b)

**Comment by argorar** [comment]
Do you use mpv?

**Comment by kirbco** [comment]
I use PotPlayer.
