### ISSUE TITLE
Unsynchronized audio issue

### ISSUE THREAD

**Issue by rbo23** [argorar/WebMConverter#106]
Hi, thank you for keeping this project alive and for all the fixes. I've stumbled across another bug or something...

I download various live streams from instagram or youtube and sometimes there are some "corrupted" videos that play totally fine with my MPC-HC player, but when I'm trying to trim it I'm getting unsynchronized audio on the output.
Here's an example video
https://mega.nz/folder/m64kWQqD#14NzwuacBUP7Ktc8YNo4fg
I've tried to cut out a part from 5:00 to 5:20 with params
>  -c:v h264_nvenc -pix_fmt yuv420p -threads 12 -slices 4 -lag-in-frames 16 -auto-alt-ref 1 -ac 2 -c:a aac -qmin 28 -crf 30 -qmax 32 -qcomp 1 -b:v 0

So I have to convert the video with a plain command line ffmpeg, parameters are the same. It complains a lot with an error
> Application provided invalid, non monotonically increasing dts to muxer in stream 0
> pts (53991) < dts (53992) in stream 0

But... plain ffmpeg does the job and the output video is fine.
Is it possible to fix it somehow? Thanks again

**Comment by argorar** [comment]
Unsynchronized audio is related to avisynth proxy and the use of third party libraries that can't handle "broken videos", at my side will not be fixed.

**Comment by argorar** [comment]
Add new option to use only ffmpeg, this fix audio synchronization problems and duplicate frames. Check the option in *Encoding* tab.
