### ISSUE TITLE
Converting GIF to WebM loses its transparency

### ISSUE THREAD

**Issue by pesonen** [argorar/WebMConverter#19]
I wanted to try if I could reduce GIF's file size by converting it to WebM but I discovered that the converter will drop the transparency in progress.
I was able to get it on Shutter Encoder program where the function is set to VP9 with alpha channel enabled on "advanced features" section. I couldn't see what parameters that program was using to achieve it.

Original/ source GIF: https://a.pomf.cat/ucosko.gif
WebMConverter result: https://a.pomf.cat/ensbzy.webm
Shutter encoder result: https://a.pomf.cat/bpasnb.webm

Cheers!

**Comment by argorar** [comment]
Try 3.18.5 version. Open the program and update.

**Comment by pesonen** [comment]
Works as intended. Thanks mate! 👍
