### ISSUE TITLE
A few notes.

### ISSUE THREAD

**Issue by Ogrlemonsoup** [argorar/WebMConverter#2]
Hello. First of all, I like your converter. But there are a few notes.
"Arguments" field do not work as expected, manual editing does not affect the result.
The converter cannot find a video track with the V_AV1 codec.
It would be nice to have an Unsharp filter.
And since there is youtube-dl and ffmpeg, you can add the option to download only a specific part(or close to it, depending on the keyframe) of the video. It would be useful.
Thank you.

**Comment by argorar** [comment]
Hello. 
Every time that you click *Convert* the application structure the arguments depending of the user selection on the interface. 
What are you adding or changing manually that you can not be added for the actions on interface?

I will check the other notes.
