### ISSUE TITLE
Video Error

### ISSUE THREAD

**Issue by XM-177** [argorar/WebMConverter#20]
I get repeated frames at the very beginning of a both a preview and an encode. The looped frames only happen on the first loop of a preview (after that it's smooth) and they're always in the actual encoded file. This behavior happens before any setting are applied and with a fresh install/update.

**Comment by argorar** [comment]
Try latest version, 3.18.8.

**Comment by XM-177** [comment]
Yeah, that fixed it up. Thanks!
