### ISSUE TITLE
Subtitles don't sync correctly

### ISSUE THREAD

**Issue by dupespra** [argorar/WebMConverter#21]
The subtitles and the video are not in sync. Example using this [YouTube video](https://www.youtube.com/watch?v=T6HOwfzKn6I):

YouTube screencap
![imagen](https://user-images.githubusercontent.com/115831435/195922654-855605c7-030e-4406-84ff-c341d089705e.png)

Scrrencap of video encoded using WebMConverter
![imagen](https://user-images.githubusercontent.com/115831435/195922939-6721c47f-cd10-40b2-a120-f304a5e93f20.png)

It's not necessary to encode the video, it can also be seen in the preview. This happened converting to both `webm` and `mp4`.

As you can see the new video is speed up, the original frame showing at 4:00 is now shown at 3:50, if you go to the 4:00 timestamp of the new video it has the same subtitles as the YouTube one. It seems like the cause of this bug is the new video being faster than the original which makes the timing of the subtitles inaccurate.

Using default arguments for mp4 with `crf` of 30, high quality mode enabled. Full arguments: 
```
 -an -c:v h264_nvenc -pix_fmt yuv420p -threads 12 -slices 4 -lag-in-frames 16 -auto-alt-ref 1 -qmin 28 -crf 30 -qmax 32 -qcomp 1 -b:v 0
```

**Comment by argorar** [comment]
Try enabling audio and using the feature **fix desync audio**

**Comment by dupespra** [comment]
@argorar Tried but the subtitles are still out of sync, also I noticed that enabling that option caused repeated frames at the beginning similar to #20.

**Comment by dupespra** [comment]
@argorar Any update on this? I'm still getting the error.

**Comment by argorar** [comment]
Upload subtitles to more testing.

**Comment by dupespra** [comment]
Thanks just tested it and works perfectly with the video mentioned in the first post.
Just one issue, it has problems reading certain filenames. I have a `srt` file named like this:
```
[ENG] '트와이스 두목' 지효가 공식적으로 해명하고 싶은 전원 재계약 비하인드 썰은？ (TWICE, JIHYO, GQGOLF, 지큐골프, 퍼팅, GOLF) [T6HOwfzKn6I].en
```
I get this error:

![Capture](https://github.com/argorar/WebMConverter/assets/115831435/56789ff6-b46a-4c8a-ada6-8a9c7002768d)

If I change the filename to something more simple like `subs.srt` then it works correctly.

Not sure If you want me to create a new issue for this.

**Comment by argorar** [comment]
That issue will not be worked on. Since the issue is from a third party library.
