### ISSUE TITLE
v3.18.8 Full color range recordings result in darkened webm conversion

### ISSUE THREAD

**Issue by VoxSerico** [argorar/WebMConverter#22]
OBS 28.0.3 recordings with Color Range set to full looks fine in preview, but the resultant conversion is dark. Handbrake handles the colors correctly, but has limited editing options.

Encoding settings in WebMConverter: High quality mode, Constant mode, 3MiB Size limit, VP9.
OBS advanced video settings: NV12 (8-bit, 4:2:0, 2 planes), Color space Rec.709, Color range Full/Limited.
Recording in limited range would be a workaround if not for the resultant conversion being noticeably brighter than the source mkv.

Original image the ~5 second recordings are based on
![1920x1080_color_range_test_chart](https://user-images.githubusercontent.com/20872511/196309252-b3d87799-e69e-4696-9012-da982ad3a05a.png)
Limited range recording snapshot after webm conversion
![Webm Converted Limited range](https://user-images.githubusercontent.com/20872511/196309333-e55a10fb-4474-497e-98b7-dcdb292d2bdd.jpg)
Full range recording snapshot after webm conversion
![Webm Converted Full range](https://user-images.githubusercontent.com/20872511/196309337-a451d43a-4e84-46ff-9efd-af21197e7e90.jpg)

**Comment by VoxSerico** [comment]
I think that it's something about not supporting the _yuvj420p_ format

**Comment by argorar** [comment]
> I think that it's something about not supporting the _yuvj420p_ format

if you play with this in Advanced tab with the arguments?

**Comment by VoxSerico** [comment]
I've had success by adding `-vf "scale=in_range=pc:out_range=tv"` as suggested [here](https://video.stackexchange.com/questions/26106/ffmpeg-color-loss-when-encoding-to-webm)
That feels like it's wrong though and should say pc to pc instead. I'm attaching the source video.
[full-range.zip](https://github.com/argorar/WebMConverter/files/9816189/full-range.zip)

**Comment by argorar** [comment]
Try version 3.18.10

**Comment by VoxSerico** [comment]
The fix as written works. The full 0-255 PC color range is represented without compression loss, and "broadcast" 16-235 range recordings are still handled as expected.

I'm guessing this was also the case for fraps videos (seeing as it's made for recording PC footage): The DarkFilter currently being applied is likely an unnecessary step and incorrectly lowers the video quality instead of selecting the correct color range.
I don't have any fraps recordings to test this hypothesis with but given [that it also checks for yuvj420p](https://github.com/argorar/WebMConverter/blob/b19d65c57af29b7c23c42828d23a1c5f91bbd49c/MainForm.cs#L1617), the cause was probably the same incorrect range conversion.
