### ISSUE TITLE
convert to mp4 doesn't work for twitter

### ISSUE THREAD

**Issue by randoomdude** [argorar/WebMConverter#23]
if you convert to mp4, you still can't upload them to twitter anything you can do about that?

**Comment by argorar** [comment]
Try version 3.18.9

**Comment by randoomdude** [comment]
Did anything change? Still can't put converted .mp4s on twitter
![image](https://user-images.githubusercontent.com/6027132/198937122-a787df4f-26b2-49e5-a662-25ead3985f84.png)

**Comment by argorar** [comment]
Try other video. Recent converted with audio and uploaded fine.
![screen](https://user-images.githubusercontent.com/9936760/199058798-bd259875-facc-4a60-ac12-93de15103841.png)

**Comment by randoomdude** [comment]
![image](https://user-images.githubusercontent.com/6027132/201594141-6e4d2fc8-af5f-4e01-b85d-6dae43bde780.png)
![image](https://user-images.githubusercontent.com/6027132/201594157-b487051b-cba8-4495-99df-b69773a9f215.png)

I've tried like 6 other videos since then, all different mp4s/webms converted to mp4 in the program and none of them are compatible with twitter

**Comment by randoomdude** [comment]
https://user-images.githubusercontent.com/6027132/201594440-2cc6049e-13a9-4fa5-979a-e4013973a8ec.mp4
ChangChingChong-1.mp4

**Comment by randoomdude** [comment]
I don't know why unless I'm using some different version, they were already encoded and didn't work, my version is totally up to date though so I have no idea why

**Comment by randoomdude** [comment]
sorry didn't see your post from earlier, still doesn't work on latest releases
![image](https://user-images.githubusercontent.com/6027132/206382355-f526fe2d-f1b5-4b2c-814e-4120f8e9b120.png)

**Comment by randoomdude** [comment]
also this exited ffmpeg.exe with code 1 shows up a lot when I use .mp4 conversion, not every time but I'm not sure what causes it or if it's related
![image](https://user-images.githubusercontent.com/6027132/206383511-eacb8888-f0c5-40f9-80f0-3c23fe126723.png)

**Comment by randoomdude** [comment]
Also an interesting note is that these .mp4's that get processed don't seem to embed in Discord properly, even though I can view them normally in mpc-hc

**Comment by randoomdude** [comment]
Updated, still can't
![image](https://user-images.githubusercontent.com/6027132/206676056-b0dd4864-fb6c-4e9c-b96e-070c60fcafd3.png)

https://user-images.githubusercontent.com/6027132/206676624-c62b4c54-4e40-4b4c-a9a6-303bf4481a44.mp4

**Comment by argorar** [comment]
> also this exited ffmpeg.exe with code 1 shows up a lot when I use .mp4 conversion, not every time but I'm not sure what causes it or if it's related ![image](https://user-images.githubusercontent.com/6027132/206383511-eacb8888-f0c5-40f9-80f0-3c23fe126723.png)

And with this settings? You share a new one every time

**Comment by randoomdude** [comment]
with basically the same settings, that one is pretty minor by comparison though, I just want the .mp4s to covert and work properly

**Comment by argorar** [comment]
https://whoihavetobe.com/video-not-embedding-discord/

Use libx264 instead of libx265 in Advanced>Arguments.

**Comment by randoomdude** [comment]
That did it, thank you, I am the only one whose has it at 265? Is it not normally 264 by default?
