### ISSUE TITLE
webm audio from youtube desynchronized

### ISSUE THREAD

**Issue by twotone8** [argorar/WebMConverter#26]
Love the utility.
I find that audio is often desynchronized when downloading/loading larger youtube videos.  They seem to default to the .webm format.  Desynchronized in the 'preview' pane and after final output, although other media players can play them just fine with proper sync.
edit: I've tried enabling the 'fix desync audio' checkbox with no change

**Comment by argorar** [comment]
Do you used embedded feature to download from youtube?
How long is the video?

**Comment by twotone8** [comment]
I did indeed.  the resulting downloaded video seems to arrive synced for some videos but not others.  Is there a way to request downloading a mp4 instead of a webm for editing purposes?  I've never had a problem with an mp4 downloaded from external players as far as audio synchronization.   Length does not appear to be a factor.  Here an example of a video that arrives desynched when downloading directly from the player.
https://www.youtube.com/watch?v=tkBVDh7my9Q

**Comment by argorar** [comment]
With that video in mp4 format is synced, isn't in webm.
To select the format go to WebMConverter\Binaries\Win64 and write cmd in address bar.
![imagen](https://user-images.githubusercontent.com/9936760/204070552-cd8a9824-e74e-45e5-8794-a091e3e3fc9f.png)

Write next command to list formats
``` yt-dlp.exe --list-formats https://www.youtube.com/watch?v=tkBVDh7my9Q```

![imagen](https://user-images.githubusercontent.com/9936760/204070627-f0253c0e-694b-4f1a-855d-e2ff095fda78.png)

Select the format do you want
``` yt-dlp.exe -f 18 https://www.youtube.com/watch?v=tkBVDh7my9Q``` 

![imagen](https://user-images.githubusercontent.com/9936760/204070745-5935a24b-8495-4f94-bdf6-6e50fcdf2dfa.png)

**Comment by argorar** [comment]
For this work around added a feature to do it easily, check option in tab General.

**Comment by twotone8** [comment]
Just tested, and it works wonderfully.  Thank you.
This is an incredible time-saver and an incredible piece of software.  Thank you for going above and beyond.
