### ISSUE TITLE
Feature/QoL: Add ability to input exact frame number

### ISSUE THREAD

**Issue by randoomdude** [argorar/WebMConverter#29]
I find sometimes when you already know what frame you want to go to, having to use the seek bar to get there can be a pain, especially if it's loading slowly, being able to hit the frame number and have it ask you to enter what frame you want exactly and go there might be useful
![image](https://user-images.githubusercontent.com/6027132/212501364-ceff54b8-b471-4da7-aa67-ea82cd34113f.png)

**Comment by argorar** [comment]
Try it. ![Captura de pantalla (28)](https://user-images.githubusercontent.com/9936760/212792823-56592f2f-69c6-44f1-99e4-23bd2a5a6d84.png)
