### ISSUE TITLE
[SUGGESTION] FastFlix (features) inspiration

### ISSUE THREAD

**Issue by forart** [argorar/WebMConverter#3]
Hi there, your converter looks very cool so we wanna suggest you to check out [FastFlix](https://github.com/cdgriffith/FastFlix) to get some inspirations about features:

![FastFlix GUI](https://raw.githubusercontent.com/cdgriffith/FastFlix/master/docs/gui_preview.png)

Last but not least, a collaboration between both softwares would be great.

Hope that inspires.

**Comment by argorar** [comment]
Thanks for the suggestion, I will check it. I am open to collaborations and contributions to the project.

Since it is not a issue i will close it.
