### ISSUE TITLE
vtt subtitle support

### ISSUE THREAD

**Issue by blueslippers** [argorar/WebMConverter#30]
Can you possibly support vtt subtitles in the future? I sometimes download youtube videos with subtitles but unfortunately the program throws me errors that avisynth cant read vtt files.
I also embedded the vtt files on the video but it cannot see the internal subs.

**Comment by argorar** [comment]
Unfortunately the latest plugin has this issue https://github.com/pinterf/xy-VSFilter/issues/33

**Comment by argorar** [comment]
Support added, check latest update.
