### ISSUE TITLE
Crop dimensioning

### ISSUE THREAD

**Issue by carcaroth** [argorar/WebMConverter#31]
In Crop menu (or under Set Dimensions), an option to choose one of the most common aspect ratios (AR) such as 1:1, 4:3, 16:9, 9:16, etc. could be available.

Initial crop box size could be set using the chosen AR and considering input video dimensions instead of some default value.

The crop box AR becomes fixed even when modifying its size via mouse or by typing a height or a width value (changing one value would automatically change the other to keep the same AR).

**Comment by argorar** [comment]
First two formats included 16:9, 9:16.

**Comment by argorar** [comment]
* Add 1:1 aspect ratio
* Improved edit *Crop* size with keyboard. keep aspect ratio with ```Ctrl + arrowKey```

**Comment by carcaroth** [comment]
Hi

Thanks for the implemented features.
Great job!

Cheers
