### ISSUE TITLE
Option to skip loading subtitles?

### ISSUE THREAD

**Issue by turkbro** [argorar/WebMConverter#32]
It takes forever if the video is long and has many subtitles, which you won't even use.
It would be nice to be able to skip/disable loading subtiltes.

Thanks for the work.

**Comment by argorar** [comment]
I wonder how long is that video. In a test 4K movie, 2:20:00 long, loading subtitles take few seconds.

**Comment by turkbro** [comment]
This file has 40 subs for example.

[output.webm](https://user-images.githubusercontent.com/106563025/214576373-0775306b-13d5-4d49-b886-00a290224acc.webm)
