### ISSUE TITLE
Crashing while using the trim tool

### ISSUE THREAD

**Issue by ZecChelovek** [argorar/WebMConverter#33]
Hello. Fine tool you have here. I consistently crash when using the trim tool to playback certain parts to get the right clip. Windows 10 64 bit.

**Comment by argorar** [comment]
It happens often with the latest version 3.22.0?

**Comment by fhtdtdj** [comment]
can confirm it's happening a lot for me too since recent updates.

**Comment by argorar** [comment]
Memory management is improved. The program is 32 bits for dependency of some libraries, so the amount of memory is limited compared to 64 bits.
