### ISSUE TITLE
add the option to convert videos in bulk

### ISSUE THREAD

**Issue by eliardneru** [argorar/WebMConverter#34]
this option would be useful for people who need to convert lots of videos, doing it manually is a pain in the ass

**Comment by argorar** [comment]
Added in version 3.24.0.

**Comment by GideonLovecraft** [comment]
And where? Can't see it in updated version and can't see 3.24 in releases

**Comment by argorar** [comment]
Opening the program it automatically check for latest update and download from it. The release is added.
