### ISSUE TITLE
Feature Request(?): Changing playback speed (rate) for only part of the video

### ISSUE THREAD

**Issue by QuantumToasted** [argorar/WebMConverter#35]
Hi there. I love using this tool to make quick edits of gameplay clips to send to friends and sometimes I desire the ability to make **part** of the clip play in slow-motion, but from what I can tell, the Rate effect can only be applied to the entire clip, and not just a small section of it.

While I'm aware this tool is (or was) just really meant to easily make small videos for posting on various Malaysian basket weaving websites, and turning this into a full-fledged video editor might be out of scope, but this would be a handy reason to not open a whole video editing suite just for quick clip editing.

Ideally, one could simply specify a From and To field in the Rate controller, to make it apply from and to the specified part of the clip. (I could see this being an issue with clips that have been **Trim**med already as maybe the program is not aware of the new clip length until after conversion?)
![image](https://user-images.githubusercontent.com/30324210/218342571-42b4ccd5-062d-4db6-ab9a-af1d1fa709a7.png)

**Comment by argorar** [comment]
Feature added, check tutorial to learn how use it.

**Comment by SamuelBucher** [comment]
Could you remove the 200% cap on the dynamic rate?
