### ISSUE TITLE
Request: Dark Mode

### ISSUE THREAD

**Issue by ZachFett** [argorar/WebMConverter#38]
Any chance we could get a dark mode setting? My eyes would thank you.

**Comment by argorar** [comment]
For how it was designed many years ago implement it is many work(changing each component). One workaround is patching windows and using a dark theme (that affect all the system).
![dark](https://user-images.githubusercontent.com/9936760/225761754-55aaa247-0c4b-4179-adc8-5e1b2fd0443c.png)
