### ISSUE TITLE
Issue when using this repo for Windows 10.

### ISSUE THREAD

**Issue by zydjohnHotmail** [argorar/WebMConverter#4]
Hello:
I found this repo, and I would like to take a try.
I downloaded the source code, updated all nuget packages, and try to run this.
My OS is Windows 10 (Version 21H1)
But I got this run time error:
You need Microsoft Visual C++ 2010 (x86) for the full experience.
The URL in the message box for downloading Microsoft Visual C++ 2010 is not working.
And I can't install even the URL is good one, as I am using Visual Studio 2019 (Version 16.11.3) and I already installed a lot of C++ packages, so I can't install any older version of C++ packages.
Please advise on how to fix this?
Can you update the C++ requirement to the latest version, so I don't have to install any C++ packages.
Thanks,

**Comment by argorar** [comment]
Hello. Please try this link https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe

Let me know if this package work for you to update the code to be helpful for others.

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply.  Yes, I downloaded the package in your URL, then I can run your repo to convert MP4 file to WebM file.
But I want to know if I can use your repo to run some Avi Scipt on MP4 file.
Thanks,

**Comment by argorar** [comment]
You can add any effect, transformation of avisynth as plugin with .dll format, then you add the arguments (also native arguments) to the general script to generate the video as you want.
