### ISSUE TITLE
the size limit calculator is still pretty much broken

### ISSUE THREAD

**Issue by 6-bullets** [argorar/WebMConverter#41]
this is a 27 seconds clip (its about 1 minute but i trimmed it), i putted the size limit as 4 mb
other than the fact that it cutted 1 second from the clip, which is pretty annoying, it just shits itself and does not manage to do it right
![image](https://user-images.githubusercontent.com/74941858/233873579-99ea18ed-8545-4147-9212-f68dcedf76d1.png)
log says its 1400 kbps
![image](https://user-images.githubusercontent.com/74941858/233873734-41f4c9a1-0350-4efa-9a7f-506f38828494.png)

it says "Restraints are too high!" even tho i resized, trimmed, did everything, and it not only wasnt able to keep it less than 4 mb but surprassed it and cutted out a little bit of video at the end, something is really broken

**Comment by argorar** [comment]
![imagen](https://user-images.githubusercontent.com/9936760/233875720-4d905df0-9151-4a80-aba5-da6dc82fcdb3.png)
Upload file.

**Comment by 6-bullets** [comment]
its porn :(

**Comment by 6-bullets** [comment]
here https://litter.catbox.moe/o33ru1.mp4

**Comment by argorar** [comment]
With this configuration and VP9 enable.
![imagen](https://user-images.githubusercontent.com/9936760/233878357-0e181077-8d52-4d33-8ce9-538d4f8c3413.png)
Just trimmed at 28 seconds, even more frames, this is the result. 
![imagen](https://user-images.githubusercontent.com/9936760/233878502-a52ab32d-81e9-47fa-a87d-c7628a524b41.png)
![imagen](https://user-images.githubusercontent.com/9936760/233878542-5fa53514-eb86-4924-a177-2d9dfffe7f7b.png)
Do you have latest version?

**Comment by 6-bullets** [comment]
yes im using 3.24.0, let me test those configs

**Comment by 6-bullets** [comment]
high quality fixes the issue completly, i think you should add a note relating to that so people dont have this issue

**Comment by argorar** [comment]
Great. I will close the issue.
