### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by carcaroth** [argorar/WebMConverter#42]
Hello

Under Encoding->General there is a box for a string of text to the metadata of the video.
By default it inserts the source video file name. I always delete the string manually every time as I don't want to use it.
A request is to have some option/tick box to leave it always blank, vs. current implementation.
Maybe even a 3rd option to use the destination file name if someone wants it.
Whatever settings are selected, should be saved permanently.

Cheers.

**Comment by argorar** [comment]
Check latest version.

**Comment by carcaroth** [comment]
Thanks, that's it.
