### ISSUE TITLE
Request: Volume Normalization Options

### ISSUE THREAD

**Issue by twotone8** [argorar/WebMConverter#44]
Love this app.
Any chance of getting some audio normalization options?

**Comment by argorar** [comment]
How do you normally do it?
I have test `-filter:a "volume=0.5"` with ffmpeg but not a big difference

**Comment by twotone8** [comment]
I can add this argument in the 'advanced' windows to achieve the result using avisynth:
Normalize(0.98)

It would be lovely if there were a checkbox to normalize audio.
Thanks for the reply

**Comment by argorar** [comment]
Check the latest update.

**Comment by twotone8** [comment]
Thank you.  This will be quite handy.
I see the option, and it is working. Set to 1.00 by default.
Is there a way to disable the normalize option?  Or will it always be on?

**Comment by argorar** [comment]
Normalize audio only is applied when the value is different of 1.00, otherwise it will not make an effect.
