### ISSUE TITLE
is it impossible to make longer webms? 50sec?

### ISSUE THREAD

**Issue by 1sad** [argorar/WebMConverter#46]
im trying to make a 50 second 4mb file but i cant get the filesize below 8mb even if i set the bitrate manually to 40.
setting filesize it cuts off like 25 seconds off it.

**Comment by argorar** [comment]
> With this configuration and VP9 enable. ![imagen](https://user-images.githubusercontent.com/9936760/233878357-0e181077-8d52-4d33-8ce9-538d4f8c3413.png) Just trimmed at 28 seconds, even more frames, this is the result. ![imagen](https://user-images.githubusercontent.com/9936760/233878502-a52ab32d-81e9-47fa-a87d-c7628a524b41.png) ![imagen](https://user-images.githubusercontent.com/9936760/233878542-5fa53514-eb86-4924-a177-2d9dfffe7f7b.png)

Try this configuration

**Comment by 1sad** [comment]
tested with that. i guess it only works properly with long files if its vp9. vp8 fails like i described. 
vp9 is extremely slow compared to vp8 though. x0.65. vs x0.15 (x0.07) in high quality mode.
is there no way to speed it up?

**Comment by argorar** [comment]
That is how VP9 works. To speed up you need a more capable cpu. I think you are a little ambitious to want to put 50 second in 4 mb, since is not a every day use case and there is  workaround I will close it.
