### ISSUE TITLE
Wrong dimension in resize window after adding a crop

### ISSUE THREAD

**Issue by dupespra** [argorar/WebMConverter#48]
May be related to this one #27. 
Similar to that issue, after you make a crop and add a resize, the dimension displayed will have 2 extra pixels

How to reproduce (I used a 3840x2160 mp4 video):
- Add a crop (in my case 1920x1080)
- Double click the crop icon to edit
- Move the crop selection around and click confirm
- Add a resize and you will see the wrong dimension (1922x1080 or 1920x1082)

**Comment by argorar** [comment]
Fixed, please check latest update.
