### ISSUE TITLE
Feature Request: Set target framerate

### ISSUE THREAD

**Issue by floppyD** [argorar/WebMConverter#51]
Sometimes you may want to change the rate of a 60fps video to lets say 400%, that would result in a 240fps video that's is often way too big. The old Webm for Retards had an option to set a target framerate to whatever you wanted, so you could just set it to like 30fps in this case and call it a day.
I'm aware there's this "interpolate" option, but I'm not sure if it works for a lower target framerate. If it does, it doesn't work well, since I tested it on this video I was trying to convert and it was giving me an encode time of only 1.5-2fps on a Ryzen 3600, while default was 70-80fps.

**Comment by argorar** [comment]
Check the latest update.

**Comment by floppyD** [comment]
Thanks!
