### ISSUE TITLE
Fix Audio desync missing in latest version

### ISSUE THREAD

**Issue by jack-cole** [argorar/WebMConverter#52]
After updating the latest version, The Fix Audio Desync option is missing. Now my videos have out of sync audio when I convert them.

![image](https://github.com/argorar/WebMConverter/assets/5460372/5fc27ee5-c450-4c83-816a-acdf9040a3b2)

**Comment by argorar** [comment]
Upload a test file.

**Comment by jack-cole** [comment]
Here is the full video that plays fine in MPV. https://drive.google.com/file/d/1y0PpC8G3bwBquwu7MHmDmomfhxmlHu5H/view?usp=sharing When I use this to trip the last part where I am in the car and get shot, the audio is desynced by a few seconds. https://drive.google.com/file/d/1URJisQmSuGffpXPyK3R4Na_e6SV6Tx1b/view?usp=sharing

**Comment by argorar** [comment]
You updated shadowplay recently?
I have a test file made with shadowplay that syncs well. Your video doesn't work with previous webm versions without weird artefacts.

**Comment by jack-cole** [comment]
Shadowplay uses variable framerate, so when a game's framerate dips so does the recorded video, which causes issues with syncing the audio. I don't know how MPV and other video applications are able to sync it. I have it set to record at 30FPS, but you can see in the first screenshot it's less than that for the video I sent, while the second screenshot is one without dips.

![Video with dips in framerate](https://github.com/argorar/WebMConverter/assets/5460372/a7fc9cb6-50d8-4753-bd38-40aeb51c01e1)

![Video with no dips in framerate](https://github.com/argorar/WebMConverter/assets/5460372/6f61e018-bb59-4a53-9bf8-888d27bbb30d)

**Comment by argorar** [comment]
With second file at 30FPS sync right?

**Comment by jack-cole** [comment]
> With second file at 30FPS sync right?

Both are VBR, but I guess the second one is able to keep it steady enough where it won't go out of sync when I encode the last 10 seconds of it with WebMConverter. Here is more details about it

```
Format settings, Reference frames        : 3 frames
Format settings, GOP                     : M=1, N=30
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 5 min 0 s
Bit rate                                 : 44.6 Mb/s
Width                                    : 2 560 pixels
Height                                   : 1 440 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 30.000 FPS
Minimum frame rate                       : 28.231 FPS
Maximum frame rate                       : 31.746 FPS
```

**Comment by jack-cole** [comment]
These are the settings I use. It chooses 29 fps for that video that has frame dips.
![image](https://github.com/argorar/WebMConverter/assets/5460372/f2ca2f4b-1e5c-49c5-a5e1-cb21477e0f05)

**Comment by jack-cole** [comment]
#17

**Comment by argorar** [comment]
Your file has different values of tbr:
![imagen](https://github.com/argorar/WebMConverter/assets/9936760/d290a51f-2d2a-436b-beec-b726babd23f3)
Video recorded with shadowplay, correct tbr:
![imagen](https://github.com/argorar/WebMConverter/assets/9936760/ba65f72b-367b-4ac5-ad7a-aa973db3cb7d)

**Comment by argorar** [comment]
> #17

The video provided in that issue sync correctly in latest version.

**Comment by jack-cole** [comment]
I set my FPS to 30 to save filesize, so the TBR is 30.
![image](https://github.com/argorar/WebMConverter/assets/5460372/cb3631f7-b2ae-45e3-9bdc-d1122ca166e8)

**Comment by argorar** [comment]
That mess internal calculations to determine exact times. If posible use another configuration like 24 fps and test again.

**Comment by jack-cole** [comment]
I used another application called Handbrake and it was able to sync the audio fine when trimmed to those last ten seconds. I prefer WebMConverter over that since it has a better UI and features.

![image](https://github.com/argorar/WebMConverter/assets/5460372/38772101-9869-4a66-9d59-79f449d6393b)

https://github.com/argorar/WebMConverter/assets/5460372/536a1e96-fcd9-4818-ab63-1cacc4dca3a7

**Comment by argorar** [comment]
It will not in short term. The dependencies with third party libraries make much harder to fix issues related to codecs because the development is dead. 

Support in this matter will be dropped from now.

Maybe, one day, these dependencies will be erased to use instead just ffmpeg.
