### ISSUE TITLE
A few ideas

### ISSUE THREAD

**Issue by Defreezer** [argorar/WebMConverter#53]
Very impressive work you've done with this so far. If I may make some suggestions:

- Perhaps rolling both Trim options into one? Sometimes I choose Trim instead of Multiple Trim only to find out that there's a section in the video I'm trimming that I'd do without, so I have to remove the Trim filter and start over with Multiple Trim, which already does the same job even if you only trim one piece of a video anyways;
- A "Mono Audio" option in the audio encoding section would be great for halving audio filesize. I know I can already set -ac 1 in the advanced tab but the convenience would be neat.

**Comment by argorar** [comment]
Can you explain more the "mono audio" use case?

**Comment by Defreezer** [comment]
Sometimes when I need to further reduce filesize for a small webm, converting the source's stereo audio to mono is a good way to do it instead of sacrificing bitrate, framerate or resolution. In many of these cases, switching from stereo to mono isn't too noticeable especially when you already resort to reducing audio bitrate in order prioritize video quality. Of course it's already possible to do it via the Advanced tab, but I was musing about having a checkbox in the Encoding tab for it as a minor convenience. Just a thought.

**Comment by argorar** [comment]
Check release notes and latest version.

**Comment by Defreezer** [comment]
Both options are working nicely. Many thanks.
