### ISSUE TITLE
Crash when launched from Windows Search

### ISSUE THREAD

**Issue by turkbro** [argorar/WebMConverter#55]
WebMConverter.exe does not launch and leaves a crash dump file in CrashDumps folder when I launch it through Windows 11's start/search functions.
It works fine when I launch it from the taskbar icon or its shortcuts.

Not a big deal for me but I wanted to report the issue.

I am attaching a couple of .dmp files from the crashes, which I don't know how to read anyway.

Thanks for the work.

[WebMConverter.exe.19248.dmp](https://github.com/argorar/WebMConverter/files/13329666/WebMConverter.exe.19248.dmp)
[WebMConverter.exe.7044.dmp](https://github.com/argorar/WebMConverter/files/13329667/WebMConverter.exe.7044.dmp)

**Comment by argorar** [comment]
Added shortcut to start from right click menu over .exe?

**Comment by turkbro** [comment]
Yeah, I think Windows was trying to launch a shortcut that I had removed from Start.
After pinning the exe to Start again, search+launch works fine.
