### ISSUE TITLE
Request: Support yt-dlp `--download-sections` parameter

### ISSUE THREAD

**Issue by shipurjan** [argorar/WebMConverter#57]
yt-dlp has a parameter that allows for downloading only parts of a video:

https://github.com/yt-dlp/yt-dlp#download-options
```
--download-sections REGEX       Download only chapters that match the
                                regular expression. A "*" prefix denotes
                                time-range instead of chapter. Negative
                                timestamps are calculated from the end.
                                "*from-url" can be used to download between
                                the "start_time" and "end_time" extracted
                                from the URL. Needs ffmpeg. This option can
                                be used multiple times to download multiple
                                sections, e.g. --download-sections
                                "*10:15-inf" --download-sections "intro"
```

For example `--download-sections "*5:35-5:45"` would only download the video section between around 5:35-5:45 (in practice it's a bit more than that, about 5:31-5:45)

It would be great if this was included in some menu in the download button, because if a user only wants to cut a short portion of a long video, then they need to download a few GBs of video, most of which is unnecessary. So this would speed things up and make it more user-friendly.

**Comment by argorar** [comment]
What about add ```url#*5:35-5:45``` in the current text box? instead of a menu or a configuration field that would add more clicks and add cognitive complexity

**Comment by shipurjan** [comment]
Sure, that sounds good too. But maybe use a symbol that can't occur in URLs like @, because while # isn't probably being used in YouTube URL links, it can be ambiguous. Just an idea, I'm not sure if it matters that much. But yeah the text form input would be fine too

**Comment by argorar** [comment]
Check latest update.
