### ISSUE TITLE
Resize function not working

### ISSUE THREAD

**Issue by LEARJS** [argorar/WebMConverter#58]
I've been having this problem for the longest time. Whenever I click the Resize button, the program freezes unable to do anything or exit until I terminate it in task manager. I tried different sources with different extensions (mp4,mkv,webm...) with reasonable sizes between 20mb to 200mb and I tried 5 different versions of the program between 3.18 to 3.31. 
No one is reporting the same issue so I figured the problem must be from my end and I wanted to ask, what might be the problem? 

I'm running Windows 10 pro 64-bit.

**Comment by argorar** [comment]
You did a fresh install, right?

**Comment by LEARJS** [comment]
For Windows? No, but I tried it on both my laptop and my PC.

**Comment by argorar** [comment]
No, I meant downloading from releases, rar with latest dll.

**Comment by LEARJS** [comment]
Yes, completely deleting the previous version each time.

**Comment by argorar** [comment]
I don't have more reports of this. Also nothing special is done under hood different as trim or crop filter.

**Comment by LEARJS** [comment]
I'm suspecting there might be a program in my system interfering with this exact function somehow. For the time being, I will just resize it elsewhere when needed.
