### ISSUE TITLE
Cannot work anymore with Avisynth portable files

### ISSUE THREAD

**Issue by Keklul404** [argorar/WebMConverter#59]
I never installed Avisynth, and until now, I was putting Avisynth files directly into the WebMConverter folder without issues.
But since WebMConverter [3.30.0], it seems to make this method not work anymore, I get a message saying that Avisynth cannot be found, no matter if I use the Avisynth from previous version, or newer versions (x86 or x64).

Would it be possible to get back on the previous way on how this was handled ?

**Comment by argorar** [comment]
Is not possible, the method was update to 64 bits. You can still use previous version and disable check for updates. Install Avisynth  will not harm your system.
