### ISSUE TITLE
webms have crushed blacks in Chrome/Safari

### ISSUE THREAD

**Issue by ll811** [argorar/WebMConverter#60]
They look as they should in Firefox but have crushed blacks in Chrome/Safari. 

primaries of mkv file I made the webm from: 
bt.709 
colormatrix: bt.601 
levels: full 

primaries of webm after conversion: 
bt.709
colormatrix: bt.709 
levels: full

webms I have made with older versions of this program that still look as they should in Chrome have levels: limited 
Top: Firefox
Bottom: Chrome
![1702848061432562](https://github.com/argorar/WebMConverter/assets/54498049/d4123722-25bb-4423-a23a-190a5cea103e)

[webm.webm](https://github.com/argorar/WebMConverter/assets/54498049/81c6b2bd-72bc-420c-bdff-4c4f21cc8bad)

**Comment by argorar** [comment]
If same file looks different from Firefox to Chrome looks more like engine updates.
