### ISSUE TITLE
is it possible to change the default setting for the encoding argument?

### ISSUE THREAD

**Issue by acgk123** [argorar/WebMConverter#62]
![image](https://github.com/argorar/WebMConverter/assets/155131410/9a1aa32b-69cf-4944-a4bd-85b68964b7dd)

is it possible to change the default H265 to H264 instead? im uploading the videos on discord and it still doesnt support H265 yet so the videos arent embedding properly in the app. i could manually edit it on the argument but just asking if theres a way i could just change the default

**Comment by argorar** [comment]
Check latest update.
