### ISSUE TITLE
Feature request: Jump to trim start and end

### ISSUE THREAD

**Issue by dupespra** [argorar/WebMConverter#64]
Add a way to quickly jump to the start or end of a trim.

Currently if you want to move the timeline cursor to either the end/start of a trim you need to manually move it or use the menu option "Go to..." and manually input the frame/time.

It would be nice to have an option to directly jump to those frames, I was thinking of two ways to do this:

1. By clicking the numbers labels, it will move the cursor to that frame/time:

![imagen](https://github.com/argorar/WebMConverter/assets/115831435/48c23984-5e59-49f9-945a-3efa4cceb051)

In this example image if you click on the start text `00:00:01 (62)` it will move the cursor to frame 62.

2. Add to the menu section "Go to..." two new items: one for jumping to start and another for the end.

Or having both these two ways would be even better.

**Comment by argorar** [comment]
Check latest update.
