### ISSUE TITLE
Auto-center when cropping

### ISSUE THREAD

**Issue by Ahherewegoagainn** [argorar/WebMConverter#66]
Hello. Not sure if this is the right place to suggest/request but would it be possible, when cropping and selecting dimensions to make it auto-center after choosing the one you want? Right now for example if I choose 9:16 it puts the selection box all the way to the left and its always a guessing game to make it completely in the center again. Thanks!

**Comment by argorar** [comment]
Crop function is to move the selection where the main object is, this isn't always perfectly in the center. The request is not accepted.
