### ISSUE TITLE
the converter ignores size limit when using "Change Rate"

### ISSUE THREAD

**Issue by most42** [argorar/WebMConverter#69]
this results in a webm with a smaller filesize than desired, with very poor image quality
in the example below, the rate was changed to 150%, with the VP9 encoders

![Untitled](https://github.com/argorar/WebMConverter/assets/46799258/a9ac45a8-acc8-4ff1-9e50-8392db9dda32)
![Untitled](https://github.com/argorar/WebMConverter/assets/46799258/b052ca53-3a63-4f22-9b25-f57d37b249d7)

**Comment by argorar** [comment]
## Issues
If you have any issues with this program, you may report them on new issue. **Add the respective video to test and configuration used if not the issue will be closed**.

**Comment by most42** [comment]
the video in question is too big to upload here directly, [so here's a dropbox link to it](https://www.dropbox.com/scl/fi/isgk4d7770kn8aec0z910/Yu-Gi-Oh-Master-Duel-2024.02.07-12.02.23.02.mp4?rlkey=ls2jcm4ueppwusn2xtlwholuf&dl=0)

and here are the settings used:
![Untitled](https://github.com/argorar/WebMConverter/assets/46799258/59412bcc-c789-4add-838f-6b31962b6497)

**Comment by argorar** [comment]
You are playing with the limit trying to convert 1 minute long clip in 4MB. Still in investigation the target final size.

Double pass, resize to 720, 1 minute long, 4MB.
[Yu-Gi-Oh! Master Duel 2024.02.07 - 12.02.23.02-5-1.webm](https://github.com/argorar/WebMConverter/assets/9936760/264f92b6-83ec-485a-bc70-2e2169eff4cd)

**Comment by argorar** [comment]
The last time that feature was touched in 3.18.3. When noticed it?

**Comment by argorar** [comment]
Happens with vp8 and vp9. The argument `-maxrate:v 519430` keep the quality in op case. I don't have an algorithm for the value tho.
![imagen](https://github.com/argorar/WebMConverter/assets/9936760/90001df9-1b75-4d13-9699-11526348b444)

**Comment by argorar** [comment]
Maybe the new method will not work 100% of the cases but is more reliable now. Check latest update.

**Comment by fhtdtdj** [comment]
Can confirm it seems more reliable with cleaner results now, thank you.

**Comment by most42** [comment]
thank you for your work, it seems to work correctly now!
