### ISSUE TITLE
Exception error when checking "Enable Audio" - Fresh Win10 install

### ISSUE THREAD

**Issue by sageTF2** [argorar/WebMConverter#7]
https://pastebin.com/TB1YBFCd

Windows 10 Education N 64bit

**Comment by argorar** [comment]
Do you have other instance running?

**Comment by sageTF2** [comment]
Hey, sorry about the issue i posted. Turns out Windows 10 Edu  N is missing
some core features that many media players and applications such as your
own webmconverter require. The "N" editions were made to comply with German
law and don't have Windows Media Player, Skype, and are missing some
important .dll dependencies commonly used apparently.
I installed Media Feature Pack and it now works perfectly. It's my fault
really, but it may be interesting for you to know about this N thing...

**Comment by argorar** [comment]
Thanks for the info. I will close the issue.
