### ISSUE TITLE
Exit Code 1 When trimming video

### ISSUE THREAD

**Issue by aliasfree** [argorar/WebMConverter#70]
Arguments for pass 1: -f nut -i pipe:0   -an -c:v libvpx-vp9 -pix_fmt yuv420p -threads 12 -slices 8 -metadata title="[Ironclad] Dungeon Meshi - 08 [10bit.1080p.AV1]" -lag-in-frames 16 -auto-alt-ref 1 -qmin 28 -crf 30 -qmax 32 -qcomp 1 -b:v 0 -aq-mode 4 -row-mt 1 -tile-columns 6 -tile-rows 2 -pass 1 -passlogfile "C:\Users\spect\AppData\Local\Temp\e1ce0299-8129-4f01-b3b3-b3c33960ac2f"  -f webm -y "NUL"
Arguments for pass 2: -f nut -i pipe:0   -an -c:v libvpx-vp9 -pix_fmt yuv420p -threads 12 -slices 8 -metadata title="[Ironclad] Dungeon Meshi - 08 [10bit.1080p.AV1]" -lag-in-frames 16 -auto-alt-ref 1 -qmin 28 -crf 30 -qmax 32 -qcomp 1 -b:v 0 -aq-mode 4 -row-mt 1 -tile-columns 6 -tile-rows 2 -pass 2 -passlogfile "C:\Users\spect\AppData\Local\Temp\e1ce0299-8129-4f01-b3b3-b3c33960ac2f"  -f webm -y "D:\Users\Alias-05\Desktop\[Ironclad] Dungeon Meshi - 08 [10bit.1080p.AV1].webm"

--- CREATING AVISYNTH PROXY --- 
[avisynth @ 0280e4a0] unknown AviSynth colorspace -1610285048
C:\Users\spect\AppData\Local\Temp\tmp7490.tmp: Unknown error occurred

[nut @ 00000229a19dd8c0] No main startcode found.
--- FFMPEG HAS EXITED ---
--- ENTERING PASS 2 ---
--- CREATING AVISYNTH PROXY --- 
pipe:0: Invalid data found when processing input
[avisynth @ 0280e4a0] unknown AviSynth colorspace -1610285048
C:\Users\spect\AppData\Local\Temp\tmp7490.tmp: Unknown error occurred

[nut @ 000001e148bfba80] No main startcode found.
--- FFMPEG HAS EXITED ---
pipe:0: Invalid data found when processing input

ffmpeg.exe exited with exit code 1. That's usually bad.
If you have no idea what went wrong, open an issue on Github and copy paste the output of this window there, also upload test video.

No test video generated, either. Using WebM for Lazys v3.35.0.

**Comment by argorar** [comment]
Use [AviSynth](http://avisynth.nl/index.php/Main_Page#Official_builds) (2.6.0, 32-bit) if have another installed.

**Comment by aliasfree** [comment]
That appears to have fixed it!
