### ISSUE TITLE
yt-dlp.exe process doesn't end after exiting

### ISSUE THREAD

**Issue by VoxSerico** [argorar/WebMConverter#72]
WebMConverter v3.36.0
yt-dlp v2024.03.10
Windows 10 x64 22H2

Starting the application fires up two new instances of `yt-dlp.exe` which remain running in the background taking up 33MB until forcibly terminated.
Closing WebMConverter does not close the `yt-dlp.exe` processes, eventually leaving many instances running in the background.

**Comment by argorar** [comment]
Fixed.
