### ISSUE TITLE
Program crashes when interpolating from 30 frames to 100

### ISSUE THREAD

**Issue by Mindawga** [argorar/WebMConverter#75]
Program works normally and perfectly fine in all other cases. My input file is 4096x4096 quicktime RGBA at 30 FPS. (length of 14 seconds). I am trying to interpolate it with alpha and export it as 100 FPS webM. This is possible when the input is at 100 FPS and interpolation is not done. The error I get is a memory allocation error. This is strange as I have 32 GB of RAM and not running anything RAM intensive (GPU VRAM is 8 GB), the input video is 3 GB in size and 14 seconds in length, I'm running the program with administrator privileges, there is no audio track and I have plenty of space in the temp folder. Console output log:

Arguments for pass 1: -f nut -i pipe:0   -an -c:v libvpx-vp9 -pix_fmt yuva420p -threads 12 -slices 8 -metadata title="Title" -lag-in-frames 16 -auto-alt-ref 1 -vf "minterpolate=mi_mode=mci:me_mode=bidir:mc_mode=aobmc:vsbmc=1:fps=100" -qmin 14 -crf 16 -qmax 18 -qcomp 1 -b:v 0 -aq-mode 4 -row-mt 1 -tile-columns 6 -tile-rows 2 -pass 1 -passlogfile "hidden"  -f webm -y "NUL"
Arguments for pass 2: -f nut -i pipe:0   -an -c:v libvpx-vp9 -pix_fmt yuva420p -threads 12 -slices 8 -metadata title="Title" -lag-in-frames 16 -auto-alt-ref 1 -vf "minterpolate=mi_mode=mci:me_mode=bidir:mc_mode=aobmc:vsbmc=1:fps=100" -qmin 14 -crf 16 -qmax 18 -qcomp 1 -b:v 0 -aq-mode 4 -row-mt 1 -tile-columns 6 -tile-rows 2 -pass 2 -passlogfile "hidden"  -f webm -y "hidden"

--- CREATING AVISYNTH PROXY --- 
Input #0, nut, from 'pipe:0':
  Metadata:
    encoder         : Lavf56.40.101
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 4096x4096, 30 tbr, 61440 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> vp9 (libvpx-vp9))
[Parsed_minterpolate_0 @ 0000020e497dc580] Failed to configure input pad on Parsed_minterpolate_0
Error reinitializing filters!
Failed to inject frame into filter network: Cannot allocate memory
Error while processing the decoded data for stream #0:0
Conversion failed!
--- FFMPEG HAS EXITED ---
--- ENTERING PASS 2 ---
--- CREATING AVISYNTH PROXY --- 
Input #0, nut, from 'pipe:0':
  Metadata:
    encoder         : Lavf56.40.101
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 4096x4096, 30 tbr, 61440 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> vp9 (libvpx-vp9))
[Parsed_minterpolate_0 @ 0000025208e7c700] Failed to configure input pad on Parsed_minterpolate_0
Error reinitializing filters!
Failed to inject frame into filter network: Cannot allocate memory
--- FFMPEG HAS EXITED ---
Error while processing the decoded data for stream #0:0
Conversion failed!

ffmpeg.exe exited with exit code 1. That's usually bad.
If you have no idea what went wrong, open an issue on Github and copy paste the output of this window there, also upload test video.

**Comment by argorar** [comment]
4096x4096 is too large for a complex process like this. Consider resize to 2K.
