### ISSUE TITLE
webm conversion results in darker video (yuv420p issue?)

### ISSUE THREAD

**Issue by Tenome** [argorar/WebMConverter#77]
I believe this is the same issue as mentioned in #22. I was able to seemingly correct it by adding `-vf "scale=in_range=pc:out_range=tv"` as mentioned in that issue thread.

yuvj* seems to be deprecated, but the autofill still puts in yuvj420p as the argument?

I've attached my video and my OBS settings. In the meantime, does anything here need to be adjusted? I haven't looked at the settings in ages, so perhaps the color space is wrong for my Nvidia GPU or something (10-bit video). 

AviSynth 2.6.0, WfL 3.39.0.

[Video](https://www.mediafire.com/file/46q4ucr4ppq1iwf/2024-05-08_23-38-20.mkv/file)

![obs64_urE2Ia7Au6](https://github.com/argorar/WebMConverter/assets/12216081/cf143d73-41c2-4bfe-b574-2c81015307a1)
![obs64_LIhXnacJ5b](https://github.com/argorar/WebMConverter/assets/12216081/16933a37-e104-4473-9478-fb17cfd2caa1)

**Comment by argorar** [comment]
You just can change your record settings for more compatible ones. Also, continue adding the arguments in advance section when you need.

**Comment by Tenome** [comment]
The linked thread says that adding `-color_range 2` fixes it. Can that not be autodetected in WfL and added to the argument line, like the other OP suggested?

**Comment by argorar** [comment]
The yuv420p10le pixel format generate more conflicts, at least on my test. No time for troubleshoot.
