### ISSUE TITLE
WebMConverter.exe is detected as a trojan

### ISSUE THREAD

**Issue by Gostavikyi** [argorar/WebMConverter#8]
https://www.virustotal.com/gui/file/004b2e4912a66db48360ef0591aac6a82b1871ef4c5d44d8a13b920ac81e9e11

This also applies to previous releases atleast from 2020 since that was the one i was still using, also yes previous releases also gets flagged.

**Comment by argorar** [comment]
Incoming update result.
https://www.virustotal.com/gui/file/2dc763ddcb2c27da01e7cf8fb2ec324dd885aad223525209be7d2c9d1d3e6fa6/detection
