### ISSUE TITLE
Resize window dialogue not opening up on second monitor

### ISSUE THREAD

**Issue by ax1121** [argorar/WebMConverter#80]
When clicking on the resize button the window to select the dimensions isn't showing up if I have the app open on my 2nd monitor. However, if I moved the app to my main monitor and clicked Resize then the window will show up as normal. It's worth mentioning, while on 2nd monitor if I click resize, I can still provide inputs and enter dimensions then press enter without the window showing up but I will be typing blind without knowing the dimensions. Furthermore, my 2nd monitor is set to 200% scaling, if I set it to 100% and then clicked Resize, the resize window will open up on my main monitor even though the app is on my 2nd monitor. However, my 2nd monitor is unusable at 100% scale for me. 

I usually do my encodes on the second monitor while I'm busy on my main monitor. It will be hard to move the app to my main monitor if I'm gaming. I know it's a trivial problem but it would be a great improvement in quality of life if it can be addressed. 

I'm using the latest version v3.39 with Windows 10. I tried older versions of the app and it's an identical problem.

**Comment by argorar** [comment]
Check latest update. If like this program give it a star :star:.
