### ISSUE TITLE
Suggestion: add option to import a PNG sequence

### ISSUE THREAD

**Issue by JustPal1** [argorar/WebMConverter#82]
It would be a real handy feature if instead of an input video I could add a PNG sequence and produce a video output. If I'm not mistaken, ffmpeg does support it. I don't believe there's a way to do this here without writing your own scrips/command lines. If this feature does exist and I somehow missed it, it would be great to advertise it more. Thanks!

**Comment by argorar** [comment]
I don't see a clear use case for the feature, the majority use own record videos or from youtube as imput. The effort worth for 0.5% of the cases?
