### ISSUE TITLE
Add hdr support

### ISSUE THREAD

**Issue by rbo23** [argorar/WebMConverter#85]
Hi. I'm trying to convert hdr video to sdr 

> Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn (default)

and facing this error
> --- CREATING AVISYNTH PROXY --- 
> [avisynth @ 0270e8a0] unknown AviSynth colorspace -1610285048

Could you add an option for changing colourspace or something to make it work?

**Comment by argorar** [comment]
Give all the information that templates require or the issue will be closed again.
