### ISSUE TITLE
Getting 'Unknown avisynth colorspace" error / unknown error when trying to covert.

### ISSUE THREAD

**Issue by Inkerlink** [argorar/WebMConverter#86]
**Describe the bug**
Tried to convert a small clip from the whole Lady and the Tramp movie in 1080p. Gives this error when trying to run the converter, and also when trying to preview the clip.

Log output:

>Arguments for pass 1: -f nut -i pipe:0   -an -c:v libvpx-vp9 -pix_fmt yuv420p -threads 8 -slices 4 -metadata title="Lady.And.The.Tramp.1955.1080p.BluRay.x265-RARBG" -lag-in-frames 16 -auto-alt-ref 1 -qmin 28 -crf 30 -qmax 32 -qcomp 1 -b:v 0 -aq-mode 4 -row-mt 1 -tile-columns 6 -tile-rows 2 -pass 1 -passlogfile "C:\Users\Shaun\AppData\Local\Temp\6252ae3d-fb5b-4bda-8998-85481e38abf8"  -f webm -y "NUL"
Arguments for pass 2: -f nut -i pipe:0   -an -c:v libvpx-vp9 -pix_fmt yuv420p -threads 8 -slices 4 -metadata title="Lady.And.The.Tramp.1955.1080p.BluRay.x265-RARBG" -lag-in-frames 16 -auto-alt-ref 1 -qmin 28 -crf 30 -qmax 32 -qcomp 1 -b:v 0 -aq-mode 4 -row-mt 1 -tile-columns 6 -tile-rows 2 -pass 2 -passlogfile "C:\Users\Shaun\AppData\Local\Temp\6252ae3d-fb5b-4bda-8998-85481e38abf8"  -f webm -y "D:\Users\Shaun\Pictures\Reactions\Webm\Lady and the Tramp\lady.webm"
--- CREATING AVISYNTH PROXY --- 
[avisynth @ 027ee4a0] unknown AviSynth colorspace -1610285048
C:\Users\Shaun\AppData\Local\Temp\tmpA23C.tmp: Unknown error occurred
[nut @ 000001b3da58dac0] No main startcode found.
--- FFMPEG HAS EXITED ---
--- ENTERING PASS 2 ---
--- CREATING AVISYNTH PROXY --- 
[in#0 @ 000001b3da58d980] Error opening input: Invalid data found when processing input
Error opening input file pipe:0.
Error opening input files: Invalid data found when processing input
[avisynth @ 027fe4a0] unknown AviSynth colorspace -1610285048
C:\Users\Shaun\AppData\Local\Temp\tmpA23C.tmp: Unknown error occurred
[nut @ 0000023c4676dc00] No main startcode found.
--- FFMPEG HAS EXITED ---
[in#0 @ 0000023c4676dac0] Error opening input: Invalid data found when processing input
Error opening input file pipe:0.
Error opening input files: Invalid data found when processing input
ffmpeg.exe exited with exit code -1094995529. That's usually bad.
If you have no idea what went wrong, open an issue on Github and copy paste the output of this window there, also upload test video.

**To Reproduce**
1. Open program and load in ladyandthetramp.mp4
2. Use clip function to make a short few seconds clip.
3. Choose output folder and filename
4. Set mode to variable
5. Either hit preview or try to convert.
6. Error appears.

**Expected behavior**
The converter should convert the clip or preview it without error.

**Screenshots**
![image](https://github.com/argorar/WebMConverter/assets/97848426/3a2c1909-ab94-430b-a591-5f6bd8aef3e2)

**Software version(please complete the following information):**
 v3.40.2

**Test File**
Don't think I can upload a test file...

**Comment by argorar** [comment]
Use [AviSynth](http://avisynth.nl/index.php/Main_Page#Official_builds) (2.6.0, 32-bit) if have another installed.

**Comment by Inkerlink** [comment]
> Use [AviSynth](http://avisynth.nl/index.php/Main_Page#Official_builds) (2.6.0, 32-bit) if have another installed.

Welp, that seems to have worked.
Thanks!

**Comment by argorar** [comment]
If likes this program give a start ⭐
