### ISSUE TITLE
"Create another" button's suffix malfunctions after 10th file

### ISSUE THREAD

**Issue by jiyuhv** [argorar/WebMConverter#89]
**Describe the bug**
After converting a file, and using the "Create another" button in the conversion progress window, the suffix breaks after the 10th file, it should go from "filename.webm-10" to "filename.webm-11", but instead it becomes "filename.webm-10-2". This happens every time the latter number hits 10, so the 20th file is "filename.webm-10-10-2".
To keep a constant numbering of output files, the only option after 10th file is to always use the "close" button, and change the number manually. 

**To Reproduce**
1. Convert 11 files and always use "create another" button in the conversion progress window after conversion is complete.
2. The suffix of the 11th file becomes "-10-2" instead of "-11".

**Expected behavior**
The suffix of 11th file should keep the constant numbering, and become "-11".

**Screenshots**
Output filename for the 22th file as an example. The suffix should be "-22" instead of "-10-10-4"
Don't think settings make a difference here, so no screenshots of them.
![WebMConverter_pWrD8W3GG0](https://github.com/user-attachments/assets/029e9340-2980-4538-b379-43aea24b3813)

**Software version(please complete the following information):**
 - Avisynth: 3.7.2
 - WebM for Lazys: v3.40.3

**Test File**
Works with any file.

**Comment by argorar** [comment]
Fixed in v3.40.4.
