### ISSUE TITLE
Can't get it to launch on Windows 10 no matter what I do

### ISSUE THREAD

**Issue by kirbco** [argorar/WebMConverter#91]
Title. I have no idea what the issue could be, but it won't work at all. I've installed all the necessary components and for some reason Webm for Retards works, but I can't get any version of Webm for Lazys to launch, even when I turn off security or run as administrator.

**Comment by argorar** [comment]
Tried a fresh install? No enough details to guide you.

**Comment by kirbco** [comment]
Yes, it is a fresh install, this is a new laptop. Forgot to mention that, sorry. I've downloaded older versions and they won't launch or do anything either.

**Comment by kirbco** [comment]
idk how but i somehow finally got it to work.

**Comment by Pentaphon** [comment]
@argorar I am having the same issue on Windows 11. It starts and asks me to install Avisynth 2.6, which I did after that prompt, but then it won't launch at all. Is there an app data folder somewhere I need to delete to start fresh?

**Comment by argorar** [comment]
Looks like this in installed software?
![imagen](https://github.com/user-attachments/assets/4d7e316b-2974-46c3-8f59-92a4266a5a33)

**Comment by Pentaphon** [comment]
> Looks like this in installed software?
![{006DB78A-CADD-4C6E-9625-22F287EF1688}](https://github.com/user-attachments/assets/4cd9e2a3-958f-4d86-962b-e45b128946d4)

Yes.

**Comment by argorar** [comment]
Try this. [WebMConverter.zip](https://github.com/user-attachments/files/18269566/WebMConverter.zip)

**Comment by Pentaphon** [comment]
@argorar just replaced my current exe with that and it still won't open. Is there something I can "reset" to make it open? It's so puzzling that I don't get any error message at all.

**Comment by argorar** [comment]
No idea what can happen. If open WebMConverter.exe from the CMD  in the directory?

**Comment by Pentaphon** [comment]
> No idea what can happen. If open WebMConverter.exe from the CMD in the directory?

@argorar just tried it and no luck there either. I'm going to try random things until it works and report back if successful.
