### ISSUE TITLE
Subtitles get cropped

### ISSUE THREAD

**Issue by dupespra** [argorar/WebMConverter#93]
**Describe the bug**
When you have a crop and subtitles, the crop cuts off the subtitles. It would be better if the subtitles get resized to fit in the crop area.

**Software version(please complete the following information):**
v3.40.4

Here is an example using this [video](https://www.youtube.com/watch?v=Y7W41VMxyQE):
![sub_bug](https://github.com/user-attachments/assets/35be2f3f-7630-404b-9727-2db2125748d2)

Added the subtitle file to this [zip](https://github.com/user-attachments/files/16826303/How.to.adjust.your.caption.settings.on.YouTube.Y7W41VMxyQE.en.zip).

**Comment by argorar** [comment]
Check latest update.
