### ISSUE TITLE
Video only / Audio only 

### ISSUE THREAD

**Issue by kirbco** [argorar/WebMConverter#97]
When choosing a format for downloads is there just no way to download videos _with_ audio? Or am I missing something?

**Comment by kirbco** [comment]
Figure it's best not to open another issue when I already have one open, so I'm adding it here. I also seem not to be able to add external subtitles anymore. Internal subtitles aren't working either, not sure why.

**Comment by argorar** [comment]
> When choosing a format for downloads is there just no way to download videos _with_ audio? Or am I missing something?

That is handle for yt-dlp, the options displayed are the available.



> Figure it's best not to open another issue when I already have one open, so I'm adding it here. I also seem not to be able to add external subtitles anymore. Internal subtitles aren't working either, not sure why.

Check latest update.
