### ISSUE TITLE
Subtitles issues

### ISSUE THREAD

**Issue by dupespra** [argorar/WebMConverter#98]
**Describe the bug**
Found two issues with the subtitles after the last update
- The subs are no longer in sync if you trim the video. The subs always start from time 0 which causes a desync if you have a trim that has a different start time than the original video.
- The subs are always centered with respect to the original dimensions of the video. If your crop is not centered the subs would be cut off.

**Software version(please complete the following information):**
v3.40.4

I attached an example using the [video ](https://www.youtube.com/watch?v=Y7W41VMxyQE) from #93, you can see there is like a shadow where the subs are supposed to be and also the timing is wrong:
[How to adjust your caption settings on YouTube [Y7W41VMxyQE].webm](https://github.com/user-attachments/assets/8c922b22-640a-4b6d-9662-70e8047cb082)

**Comment by argorar** [comment]
Check latest update.

**Comment by dupespra** [comment]
@argorar The update fixed the timing but the subtitles no longer fit within the crop area.

**Comment by argorar** [comment]
> @argorar The update fixed the timing but the subtitles no longer fit within the crop area.

Fixed.
